shnewto/bnf

- src/lib.rs
- src/node.rs
- src/parsers.rs
- src/reports.rs
Previously the BNF types implemented the ToString trait. However the
rust convention is to implement fmt::Display instead because it covers
wider use cases and automatically implements the ToString trait as well.
Now the types support format as well as to_string.
Apologies also that is change is bundled with rustfmt changes. I could not get vscode to play nice with formatting.
>  Implement format display instead of ToString

- src/node.rs
I assumed the `#[allow(dead_code)]` was leftover from development and removed them. However since I was not seeing the compiler give warnings previously, I am not sure if they were truly unnecessary.
> Remove dead code allowances

- src/reports.rs
It seems strange to me to rely on debug printing for anything user facing. Then again, maybe in this case since it is error reporting, it is acceptable? Small change, but honestly could be convinced to go either way.
> Switch reporters to using display format

- src/parsers.rs
I assumed this print was vestigial and removed it
> Remove print in grammar test

- tests/display.rs
Prior to this commit there was no test to provide assurances that changes
to the codebase would not effect the expected output implemented as the
Display trait. This commit adds a test to help provide that assurance.
> Add object display test

- README.md
Prior to this commit the branch referenced in the README's coveralls
badge was not master. After this commit the coveralls badge reflects
the state of coverage for the master branch.
> Fix branch reference in coveralls badge

- tests/display.rs
- tests/from_str.rs
- tests/generate.rs
- tests/iterate.rs
As described in the [rust book](https://doc.rust-lang.org/book/second-edition/ch11-03-test-organization.html#the-tests-directory), the tests directory is already implicitly for tests, and thus does not need the usual `test` module which unit tests use.
> Remove unnecessary integration test scope & macros

- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/term.rs
Theoretically any Grammar/Production/Expression/Term which is converted to string, and then back should maintain the same value. In order to test this property, `quickcheck::arbitrary` was implemented for each type, but only if building for tests. Hopefully these arbitrary values will be useful for future property tests. The tests using arbitrary Grammar/Production ran a little slow so the # of tests and size limit were restricted. According to travis, these tests added ~1 minute of build/test time.
> Test to_string and from_str reflexive property

- Cargo.toml
- README.md
- src/grammar.rs
- src/lib.rs
- Doc formatting and typo fixes. Remove const name case warning.
- Bump version, add the rest of the authors.
> Doc formatting and typo fixes. Remove const name case warning

- src/production.rs
I need to easily access the number of rhs `Expression`s, but the rhs `Vec` is private.
This is a quick addition to return the length of the rhs `Vec`.
> Added len() function for Production to return number of rhs Expressions

- Cargo.toml
- src/error.rs
- src/expression.rs
- src/grammar.rs
- src/parsers.rs
- src/production.rs
- src/term.rs
There should be no functional changes from this migration, however some of the parsers and error handlers needed to be updated to handle changes in nom API/behavior.
I made this change because I was looking adding a new parser for EBNF support and noticed that the nom version was 2 years out of date. If there was a reason nom 3.2 was being used, this change isn't required.
> Upgraded bnf to use nom 5.0.1

- src/parsers.rs
We have an unused variable (just a rule to eat input) that a '_' was added to to indicate it's unused as well as fix a warning
> '_' to unused var

- tests/iterate.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
> Use `slice::iter` instead of `into_iter` to avoid future breakage

- src/error.rs
- src/expression.rs
- src/grammar.rs
- src/lib.rs
- src/parsers.rs
- src/production.rs
- src/term.rs
- tests/display.rs
- tests/from_str.rs
- tests/grammar.rs
- tests/iterate.rs
Went through all of the old nom style macros implemented and took a nom 5 approach, using only functions. Some fall out from that included simplifying our error reporting, I'm not even sure why we were differentiating parse from incomplete errors in the first place...
Another part of these changes is tackling a bunch of stuff clippy warned about. The most significant change there was removing the weirdness where I was implementing FromStr for each object as well as a `from_str` in each object's impl. Now instead of seeing `let x = Object::from_str("...")`, we're using `let x: Result<Object,_> = "...".parse()`
> Phase out old nom macros

- Cargo.toml
- src/grammar.rs
- src/parsers.rs
- tests/grammar.rs
This PR includes the commits automatically created by @dependabot along with the fixes needed for the dependency version updates.
Resolves #60 
Supersedes #58 and #59
> Update rand and quickcheck dependencies

- tests/display.rs
- tests/fixtures/bnf.bnf
- tests/fixtures/postal_address.nonterminated.input.bnf
- tests/fixtures/postal_address.terminated.input.bnf
- tests/grammar.rs
This should partially address the suggestion in #79, splitting the longish, more escape-heavy bnf test fixtures into their own `.bnf` files. I decided against extracting the DNA example since it's short and emoji-based bnf examples since I didn't feel the effort would make reading the tests easier.
> chore: factor long bnf text fixtures into their own files

- .github/workflows/ci.yml
haven't been able to get a successful tarpaulin coverage report (see https://github.com/xd009642/tarpaulin/issues/756) so removing it all together for now
> remove coverage reports for now

- src/grammar.rs
I was using bnf as a fuzzer for a parser I made. I experienced a problem that was hard to solve without a change to the library. I'm using my own fork right now, but I thought it would be nice to propose these changes for upstream as well. The problem I had is that I have a grammar that allows variable names in the form `[a-zAZ_][a-zA-Z0-9_]*`. However, not *certain* names (such as 'test', which is a keyword). I could just reject all strings with the word 'test' in, however, that would never generate strings with this keyword. 
My solution is to add a  set of alternatives to `Grammar::generate()` and `Grammar::generate_seeded()` which take a callback (though I'm not yet entirely sure about the current naming). For example `Grammar::generate_callback()`. 
`Grammar::generate()` is a thin …
> add callbacks to string generation

- src/expression.rs
- src/term.rs
I implemented the BitOr Trait (`|` operator) for Term and Expression as described in #34.
This allows syntax that mirrors actual BNF like:
`let exp= Term::Terminal::from_str("A") | Term::Terminal::from_str("B") | Term::Terminal::from_str("C")`
- `Term | Term` creates an Expression that contains both Terms.
- `Expression | Term` and `Term | Expression` add the Term to the Expression.
- `Expression1 | Expression2` clones all terms from Expression2 and adds them to Expression1
I made seperate methods for `Expression` and `&Expression` to prevent unnecessary clones as recommended in  https://doc.rust-lang.org/core/ops/index.html
While testing, I noticed that two expressions are only counted as equal when their .terms are in the exact same order.
This causes strange behavior like:
`a | …
> Add "+" operator

- Cargo.toml
- benches/README.md
- benches/bnf.rs
I hope the [README](https://github.com/shnewto/bnf/pull/91/files#diff-a78b465f9dbab9f55bce48f68761be8cef21f8dc2501840b833524cd9c8f7551) explains this PR. But one additional nice thing to look at is a screenshot from the Criterion report 😍 
Obviously big caveat to the numbers. Running on my personal laptop, with other process activity, etc. But nice to see what the reports can look like!
One potential issue with these benchmarks is that `Grammar::generate` relies on random seeds. Currently there is no public API for generating with a static, controlled seed for reliable benchmarking. This introduces some chance to that benchmark, but hopefully it is small noise in the big picture. On my machine, I observed ~2% of performance drift between random `Grammar::generate` benchmarks.
> Benchmark BNF examples via Criterion

- src/earley.rs
- src/grammar.rs
This adds mermaid output for parse trees. Honestly, not sure if useful enough to warrant being merged. But it sure is nice to include in github docs, such as PRs!
```mermaid
flowchart TD
0["sum"] --> 1["sum"]
1["sum"] --> 2["product"]
2["product"] --> 3["factor"]
3["factor"] --> 4["number"]
4["number"] --> 5["digit"]
5["digit"] --> 6["1"]
0["sum"] --> 7["add"]
7["add"] --> 8["+"]
0["sum"] --> 9["product"]
9["product"] --> 10["factor"]
10["factor"] --> 11["("]
10["factor"] --> 12["sum"]
12["sum"] --> 13["sum"]
13["sum"] --> 14["product"]
14["product"] --> 15["product"]
15["product"] --> 16["factor"]
16["factor"] --> 17["number"]
17["number"] --> 18["digit"]
18["digit"] --> 19["2"]
14["product"] --> 20["mult"]
20["mult"] --> 21["*"]
14["product"] --> 22["factor"]
22["factor"] --> …
```
> mermaid formatting of parse trees

- README.md
IDK how I missed this before during #96, but rustdoc gives a warning on the `LICENSE` link. The link does actually work! But I think rustdoc gets confused by "shorthand" link paths `(LICENSE)` because there _could_ be a rust doc item by the same name.
rustdoc does *not* get confused by explicit URL paths tho, so this updates the LICENSE link to use the full URL
> full README license link

- src/grammar.rs
- src/lib.rs
`ParseTree` was not publicly exposed in rustdoc. Also once added, a few clippy warnings came up.
> public parse tree docs

- Cargo.toml
- src/expression.rs
- src/grammar.rs
- src/lib.rs
- src/production.rs
- src/slice_iter.rs
This PR adds support for size hints, which closes #94
But also while working on it, I realized I had introduced a lot of bespoke iterator types with duplicate code.
Luckily Rust has generics! So this adds a new utility `SliceIter` generic type, reducing code 🎊 
There is one sad danger with this. It is a breaking change! The public iterator types were exposed previously (e.g. `fn iter_rhs() -> CustomIter`).  This allows users to potentially rely on an explicit iterator type.
To prevent this in the future, return types have been updated to more opaque anonymous iterator types (e.g. `fn iter_rhs() -> impl Iterator<Item = &Term>`). That way, any future iterator changes should *not* be a breaking change.
> generic slice iterator w/ size hints

- src/lib.rs
Exposes `ParseTreeNode` to allow full matching of `ParseTree`s. Before, outputs of parsing couldn't be fully accessed because of the inability of construct variants of `ParseTreeNode` to match. Now, variants can be constructed and used for matching the `ParseTreeNode` enum, fully exposing `ParseTree`.
> Expose ParseTreeNode

- src/earley.rs
An original (maybe overeager!) optimization was included with Earley parsing. If there was no remaining input text, then no more predictions from the grammar were attempted. In most cases, this saves Earley some work. But the BNF crate supports empty production rules. This invalidates this optimization, because an empty production may still be successful even with no remaining input text.
This commit only removes this optimization built on that false assumption. It would be possible to reintroduce this improvement, but *only* for grammars without any empty productions.
Closes #108
> Earley predict on complete input

- src/slice_iter.rs
This is not a bug fix, and criterion saw no performance change. I saw this pattern in some code the other day and thought it was more clear. Maybe subjective!
> Clean iter mut pattern

- src/error.rs
- src/grammar.rs
- src/parsers.rs
clippy has a few new suggestions to remove explicit lifetime annotations in favor of implicit lifetimes
> fix implicit lifetime clippy warnings

- .github/workflows/ci.yml
Github actions has started giving warnings that some actions in use are out of date. Let's see if updating these actions fixes the warnings!
> update deprecated github actions

- Cargo.toml
- src/grammar.rs
The `stacker` crate isn't strictly needed.
We may not wish to use it in production.
Also, its dependency `psm` doesn't support WASM.
It can be made optional (enabled by default).
> stacker dependency optional (enabled by default)

- tests/grammar.rs
While I was fiddling with some other exploratory improvements, it came up that the generated grammar test was using the same seed for every case. The intention seems to be that the test generates truly arbitrary grammars, so this PR uses the property testing generator to seed the grammar.
TLDR: this property test was using the same grammar for every run. now it doesn't
```txt
// before
Ok(" <F>::= ''  <E> <E>\n")
Ok(" <F>::= ''  <E> <E>\n")
Ok(" <F>::= ''  <E> <E>\n")
Ok(" <F>::= ''  <E> <E>\n")
test test_generated_grammars ... ok
// after
Ok("<NJW> ::=<G> '' <toKJ>     <X> \n")
Ok("<d6> ::= \"''u\" '1|3' \n<G>::=<Mq>  \"\" <a5>   'E' \n <w> ::= <t> |  \"\" \n")
Ok(" <J>::= <t> |   <t>|  <Lu>    |  <t>\"0t\"|<V-A2l><c5><F>'\"' <e>|\"\" \n")
Ok("  <d60> ::=  <d>\n <sw--T>::=<Qu><D> '6d' …
```
> fix arbitrary grammar test seed

- README.md
- benches/bnf.rs
- src/earley/traversal.rs
- src/expression.rs
- src/grammar.rs
- src/production.rs
- tests/from_str.rs
- tests/iterate.rs
- tests/parse_input.rs
An even more silly PR, but maybe a style question. Most of BNF's examples and tests use double quotes for the string literal of terminals. This leads to a lot of escaping, and takes more space than a single quote (`\"` vs `'`).
This PR changes examples and tests to use single quotes. I don't think this matters much, but it does look better to my arbitrary eyes/brain.
The one controversial part to his that I see is that the existing `Display` implementations default to double quotes. So users who call `Grammar.to_string()` or similar will see the terminals in double quotes.
An alternative to this PR would be to update examples / tests to use `r#` string literals. This would allow for double quotes, without the need to escape:
`r#"<zip-part> ::= <town-name> "," <state-code> <ZIP-code> …
> Prefer single quotes for terminals

- src/expression.rs
- src/grammar.rs
- src/production.rs
The new `Grammar::generate` logic made sense. But benchmarking on my local machine showed ~55% performance impact (likely the recursive allocation of vectors). With a little refactoring, my local perf got back within *noise* of the performance on `main` branch.
> Reworked generate perf

- Cargo.toml
- src/error.rs
- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/term.rs
- tests/grammar.rs
A swing at addressing #70 though rather than getting any smarter about how we actually generate sentences (that can surely be improved someday), the changes in this PR implement checks that generation _can_ succeed. Aside from the tests, and a couple little things `cargo fmt` threw in there, the actual implementation is relatively short, thanks to the proposal from @notDhruv, that served me well ❤️ 
That proposal was for implementation that effectively lets us decide if generation can succeed lives here https://github.com/shnewto/bnf/issues/70#issuecomment-1356299131
I was happy to follow it to the letter, though one note if you're looking at the code, in my implementation "marking" non-terminals means adding them to a `Vec` called `terminating_rules`
This represents a breaking change! …
> Reworked generate

- .github/actions-rs/grcov.yml
- .github/workflows/ci.yml
I saw a repo the other day using LLVM to inject coverage reporting. I thought I would give it a try since `grcov` having issues.
> LLVM coverage reporting

- .github/workflows/ci.yml
- .github/workflows/tag-and-publish-crate.yaml
- Cargo.toml
- RELEASE.md
- src/error.rs
This PR adds an action that can be manually triggered to handle bumping the Cargo.toml version, adding a corresponding tag to the repo, and publishing to crates.io. The full proposed process is documented in the RELEASE.md that's been added here too.
Some things I thought about then decided against before settling on this solution:
- We could potentially add another step to the action to actually create a release as well but I opted not to in order to leave some room for the kinds of unautomatable notes that should sometimes make it into a release.
- We could publish to crates automatically after creating a release manually, but then we end up needing to manually edit the version in the Cargo.toml in order for it to be in the state of code covered in the release's tag. I don't like having …
> New release process (release with a manually triggered action)

- src/append_vec.rs
- src/error.rs
- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/slice_iter.rs
- src/term.rs
Fiddled with some code to see if coverage reporting could improve, and also make some code a little cleaner, or remove unused code entirely
> Fiddle with coverage changes

- Cargo.toml
- benches/README.md
- benches/criterion.rs
- benches/divan.rs
- benches/util.rs
Closes #138 
I ported the existing benchmarks to Divan as described in #138.
```
cargo bench -q --bench divan
Timer precision: 41 ns
divan                                  fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ examples                                          │               │               │               │         │
├─ generate_dna                     415 ns        │ 75.45 µs      │ 707 ns        │ 765.5 ns      │ 570652  │ 570652
├─ parse_infinite_nullable_grammar  999 ns        │ 2.995 ms      │ 106.4 µs      │ 146.1 µs      │ 34183   │ 34183
│                                   1 Mitem/s     │ 31.04 Kitem/s │ 469.6 Kitem/s │ 335.2 Kitem/s │         │
├─ parse_polish_calculator          4.79 µs       │ 76.19 ms      │ 11.45 µs      │ 852.3 …
```
> Divan benchmarking PoC

- Cargo.toml
- benches/divan.rs
Divan [`0.1.6`](https://github.com/nvzqz/divan/blob/main/CHANGELOG.md#016---2023-12-13) introduced [`AllocProfiler`](https://docs.rs/divan/0.1/divan/struct.AllocProfiler.html) and recently [`0.1.8`](https://github.com/nvzqz/divan/blob/main/CHANGELOG.md#018---2023-12-19) optimized it to have a minimal footprint.
Example output:
```
divan                                  fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ examples                                          │               │               │               │         │
├─ generate_dna                     540.6 ns      │ 18.12 µs      │ 874.6 ns      │ 946.2 ns      │ 432421  │ 432421
│                                   alloc:        │               │               │               │         │
│ …
```
> Profile allocations in Divan benchmarks

- Cargo.toml
- benches/util.rs
- src/earley/input_range.rs
- src/earley/mod.rs
- src/earley/traversal.rs
- src/expression.rs
- src/grammar.rs
- src/production.rs
Cargo/clippy recently added [support](https://doc.rust-lang.org/stable/cargo/reference/manifest.html#the-lints-section) for configuring lints via the `Cargo.toml`. This configures clippy lints and helps them be reliable for all contributors. And creates a central place to configure them!
> Enable clippy lints via toml

- Cargo.toml
- src/earley/input_range.rs
- src/earley/mod.rs
- src/earley/traversal.rs
- src/expression.rs
- src/grammar.rs
enable a new clippy lint which flags functions which can be `const`
> Const it up

- Cargo.toml
- src/earley/grammar.rs
- src/earley/mod.rs
- src/earley/traversal.rs
- src/lib.rs
hashbrown is the same hashmap used by the std library. however the std library uses some safer defaults (denial-of-service resistant hashing) and is a few versions behind. 
these differences may lead to performance loss when not required.
using hashbrown in BNF improved _all_ benchmarks on my local machine by 2-25%.
for this reason, it seems worth BNF adopting hashbrown as its default hasher.
the denial-of-service resistance is not required for BNF's use cases
> use hashbrown as internal hashmap

- Cargo.toml
- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/term.rs
fixes #149 and adds the new feature flag as a default to avoid breaking change, consider removing it in a future major version.
> put serde and serde_json behind a default feature flag

- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/term.rs
Adds macro constructors for each of the base BNF types (terms/expressions/productions/grammars)
```rust
let dna_grammar = bnf::grammar! {
<dna> ::= <base> | <base> <dna>;
<base> ::= 'A' | 'C' | 'G' | 'T';
};
```
Via not very easy to read, and hard to test `macro_rules` 😅
* sometimes writing a macro is nice because it is shorter than `<prod> ::= 'A'".parse()`
* it is definitely shorter than the `*::from_parts` constructors
* `macro_rules` are hard to reason about, debug, and test
* maybe offering multiple ways to do the same thing is confusing to users
* for example, because whitespace is not a token, semicolons are a hard requirement for parsing a Grammar via macros
The main motivation for this was to see if maybe a `const` constructor would be possible. The current macros do not support …
> Macro Constructors

- Cargo.toml
- src/augmented.rs
- src/expression.rs
- src/grammar.rs
- src/lib.rs
- src/parsers.rs
- src/production.rs
- src/term.rs
- src/tracing.rs
- tests/fixtures/abnf.abnf
- tests/fixtures/bnf.bnf
- tests/grammar.rs
i'm curious too hear peoples thoughts about this approach, other approaches i considered are:
```functional programming``` 
by this i mean making all the basic parsing functions higher-order functions 
so you'd pass the format as a normal parameter and it 'binds' the parameter, returning a closure that has it 
built in and thus can be composed with ```nom``` combinators
```i rejected it because``` 
it seems massively complicated to me and the use of closures would change the performance characteristics(EDIT: sic, we already use closures but they're monomorphized at compile-time, that's the whole idea behind ```nom```)
```global variables``` 
pretty self-explanatory, you have a ```static``` format with a setter and getter to hide how it's implemented, 
could be through a ```RwLock```, i …
> added Format trait to support different BNF syntaxes, and a basic implementation of ABNF  to demonstrate

- Cargo.toml
- src/error.rs
- src/parsers/augmented.rs
- src/parsers/bnf.rs
- src/parsers/mod.rs
upgrades nom to v8
I was quite surprised to see this result, and admittedly there is only one benchmark using the parsers, but:
```
parse postal            time:   [8.2610 µs 8.2783 µs 8.2939 µs]
change: [-62.857% -62.705% -62.553%] (p = 0.00 < 0.05)
Performance has improved.
```
the divan benchmarks showed the same result, likely due to about half as many allocations. so seems like some internal nom change indeed made a difference.
> upgrade nom to v8

- src/grammar.rs
- src/lib.rs
Just a small improvement (imo) to the developer experience 😄 
`rand::rngs::StdRng` is part of `bnf`'s public API, so users must have the correct version of `rand` installed.
When you also have different uses for `rand` in your codebase, you might end up doing something like this in Cargo.toml:
```toml
[dependencies]
rand = "0.9"
rand_08 = { package = "rand", version = "0.8" }
bnf = "0.5"
```
(example is for the current published state on crates.io and doesn't apply on `main`, but it could happen again in the future when `rand` releases a new version.)
By re-exporting `rand` from `bnf`, users can easily use any version they like for other purposes and use bnf's version when using `bnf`.
```rs
use bnf::rand::{SeedableRng, rngs::StdRng}; // always the right version
```
> Re-export `rand`
