- src/term.rs
- tests/display.rs
> Fix quote terminal display

- Cargo.toml
after recent fixes for things we were flagged on for future breakages on a crater run
> version bump to 0.2.7

- .github/workflows/pr.yml
- Cargo.toml
- README.md
removed custom from_str impl in favor of just implementing the FromStr trait
> minor version bump after removing an impl while getting rid of compile warnings

- CODE_OF_CONDUCT.md
> Incorporate Code of Conduct

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Thought the template wordings were a little clunky so I trimmed them down a bit.
> Editing templates

- .travis.yml
> Tarpaulin coverage reports

- Cargo.toml
- src/expression.rs
- src/grammar.rs
- src/lib.rs
- src/production.rs
- src/term.rs
> Derive SerDe for bnf objects, json is nice to use for parse results

- Cargo.toml
- src/expression.rs
- src/grammar.rs
- src/production.rs
- src/term.rs
- tests/grammar.rs
It took some manual changes/updates so dependabot's PR didn't swing it
> Update to stable quickcheck

- .github/workflows/ci.yml
> Revert "remove coverage reports for now"

- src/grammar.rs
- src/parsers.rs
Title and file changes self explanatory
> Remove unnecessary borrows and to_string()

- .github/actions-rs/grcov.yml
- .github/workflows/ci.yml
moving from codecov to coveralls, easier to toggle setting in coveralls
> revise action to use coveralls instead of codecov

- .github/workflows/ci.yml
enables Clippy during CI
Closes #46
> clippy during CI

- benches/bnf.rs
- src/earley.rs
- src/error.rs
- src/expression.rs
- src/production.rs
- tests/iterate.rs
I naively applied all the suggestions that clippy made in CI. I wanted to try to get the noise down for whoever next opens a PR 😅
> make clippy suggestions

- src/earley/input_range.rs
- src/error.rs
- src/grammar.rs
New clippy catches some lifetimes that can be elided
> fix clippy elided lifetimes

- src/parsers/augmented.rs
- src/parsers/bnf.rs
- src/parsers/mod.rs
- src/production.rs
i've removed a lot of the sequential combinators because i feel it's simpler in most cases to actually just do things sequentially
> comments are now allowed inside of any whitespace (resent because i messed up last time)

- .github/workflows/ci.yml
- Cargo.toml
- benches/criterion.rs
- benches/divan.rs
- src/grammar.rs
> upgrade rand to 0.9

- Cargo.toml
- benches/criterion.rs
- src/earley/grammar.rs
- src/earley/mod.rs
- src/earley/traversal.rs
- src/error.rs
- src/expression.rs
- src/grammar.rs
- src/lib.rs
- src/parsers/mod.rs
- src/parsers/nom_xt.rs
- src/production.rs
- src/term.rs
- src/tracing.rs
- tests/grammar.rs
* cargo fix --edition
* cargo fmt
* manual review
closes #168
> edition 2024: cargo fix --edition

- src/earley/mod.rs
- src/earley/traversal.rs
- renamed `predict_is_starting()` to `_predict` because i find the former unintuitive
- made `_predict()` return a `TraversalId` instead of `&Traversal` because most users were just taking the ID of the latter
- this also made the lifetimes less restrictive so `_predict()` can now take `self`, and  it's wrapper funcs (`predict_starting` & `predict`) no longer have duplicated destructuring code
- `match_term()` has also been made to return an ID for the same reason, which also had a similar loosening effect on the lifetimes and allowed me to remove that inner function workaround
- i also lifted a single line outside of the main match statement in `earley()`, making it a tad less verbose
...and that's about it for now
> cleaning up the earley parsing

- src/grammar.rs
This PR addresses issue #172 by clarifying the cryptographic security properties of sentence generation methods.
- **Documentation Updates**: Added comprehensive documentation to all sentence generation methods (, , , ) explaining that cryptographic security is the caller's responsibility
- **Security Guidance**: Provided clear guidance on when to use secure RNGs vs deterministic RNGs for different use cases
- **API Preservation**: Maintained the existing API while adding clarity about security implications
1. **Caller Responsibility**: Made it explicit that cryptographic security depends on the RNG implementation provided by the caller
2. **RNG Choice Guidance**: Directed users to use secure RNGs like  for cryptographic applications
3. **Deterministic Output**: Informed users about using …
> Clarify cryptographic security of sentence generation (fixes #172)

- src/grammar.rs
This PR adds comprehensive tests to prove Unicode support across all functionality of the  library, addressing issue #156.
- **Unicode grammar parsing**: Tests that grammars with Unicode terminals and nonterminals parse correctly
- **Unicode sentence generation**: Tests that random sentence generation works with Unicode content  
- **Unicode input parsing**: Tests that input strings with Unicode characters can be parsed against grammars
- **Unicode parse tree display**: Tests that parse trees display Unicode characters correctly
- **Unicode parse tree iteration**: Tests that parse tree iteration works with Unicode content
- **Unicode Mermaid formatting**: Tests that parse trees can be formatted as Mermaid diagrams with Unicode
- **Unicode grammar serialization**: Tests that Unicode …
> Add comprehensive Unicode support tests
